# Generated by Django 4.1.4 on 2023-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_preparation_steps_is_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
