# Generated by Django 4.1.4 on 2023-01-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(default=1, upload_to='recipes/covers/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
